language: python

python:
  - 3.6

sudo: required
dist: trusty
addons:
  postgresql: "9.6"

services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE="decide.settings"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "create user decide with password 'decide'" -U postgres
  - psql -c "create database decidedb owner decide" -U postgres
  - psql -c "alter user decide createdb" -U postgres

script:
  - cd decide
  - python ./manage.py migrate
  - python ./manage.py test store

notifications:
    email: false
